import type { OfficeOrder } from "@onedal/shared";

// 배차 진행(AUTO HUNT) 시뮬레이션용 현실적인 10개의 프리미엄 콜 (OfficeOrder 호환)
export const MOCK_OFFICE_ORDERS: OfficeOrder[] = [
    {
        id: "office-mock-1",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "서울 강남구 테헤란로",
        dropoff: "경기 성남시 판교테크노밸리",
        fare: 65000,
        pickupX: 127.0366,
        pickupY: 37.5005,
        dropoffX: 127.1086,
        dropoffY: 37.4020,
        itemDescription: "박스 3개 (IT 장비), 파손주의. 삼성전자 보안게이트 통과 필요.",
        companyName: "1DAL VIP 화주 (IT물류)"
    },
    {
        id: "office-mock-2",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "인천 남동구 남동공단",
        dropoff: "경기 화성시 동탄산업단지",
        fare: 120000,
        pickupX: 126.7052,
        pickupY: 37.4063,
        dropoffX: 127.0984,
        dropoffY: 37.1953,
        itemDescription: "지게차 상하차, 1파레트. 출발 전 기사님 연락 필수.",
        companyName: "1DAL B2B (제조업)"
    },
    {
        id: "office-mock-3",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "서울 성동구 성수동2가",
        dropoff: "경기 구리시 갈매동",
        fare: 45000,
        pickupX: 127.0559,
        pickupY: 37.5446,
        dropoffX: 127.1297,
        dropoffY: 37.6443,
        itemDescription: "의류 샘플 1박스 (가벼움), 수작업 상하차, 빌딩 4층 엘리베이터 있음.",
        companyName: "패션네트워크"
    },
    {
        id: "office-mock-4",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "경기 평택시 포승국가산단",
        dropoff: "충남 천안시 서북구",
        fare: 85000,
        pickupX: 126.8325,
        pickupY: 36.9921,
        dropoffX: 127.1146,
        dropoffY: 36.8550,
        itemDescription: "자동차 부품 2박스. 보안 서약서 서명 후 상차 가능.",
        companyName: "모터스물류"
    },
    {
        id: "office-mock-5",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "서울 송파구 동남권물류단지",
        dropoff: "서울 강서구 마곡동",
        fare: 55000,
        pickupX: 127.1066,
        pickupY: 37.5145,
        dropoffX: 126.8324,
        dropoffY: 37.5606,
        itemDescription: "서류행낭 1개. 점심시간(12-1시) 하차 불가피.",
        companyName: "특급로지스"
    },
    {
        id: "office-mock-6",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "경기 부천시 춘의테크노파크",
        dropoff: "인천 서구 북항로",
        fare: 48000,
        pickupX: 126.7725,
        pickupY: 37.5054,
        dropoffX: 126.6341,
        dropoffY: 37.5256,
        itemDescription: "기계 부속품 1박스, 수레 필수.",
        companyName: "하이테크ENG"
    },
    {
        id: "office-mock-7",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "경기 용인시 처인구 백암면",
        dropoff: "경기 이천시 대월면",
        fare: 70000,
        pickupX: 127.3512,
        pickupY: 37.1643,
        dropoffX: 127.4697,
        dropoffY: 37.2001,
        itemDescription: "농산물 5박스, 파손 및 변질 주의 (당일 직배송망).",
        companyName: "신선유통"
    },
    {
        id: "office-mock-8",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "서울 서초구 양재동 화훼공판장",
        dropoff: "서울 마포구 상암동",
        fare: 42000,
        pickupX: 127.0384,
        pickupY: 37.4632,
        dropoffX: 126.8906,
        dropoffY: 37.5794,
        itemDescription: "축하화환 1개, 넘어지지 않게 끈 결속 요망.",
        companyName: "플라워네트워크"
    },
    {
        id: "office-mock-9",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "경기 안산시 단원구 반월공단",
        dropoff: "경기 김포시 학운산단",
        fare: 95000,
        pickupX: 126.7451,
        pickupY: 37.3195,
        dropoffX: 126.5982,
        dropoffY: 37.6534,
        itemDescription: "금형 1개 (약 80kg), 호이스트 상하차 보조.",
        companyName: "제일금속"
    },
    {
        id: "office-mock-10",
        type: "NEW_ORDER",
        timestamp: new Date().toISOString(),
        pickup: "경기 수원시 영통구 삼성디지털시티",
        dropoff: "충북 청주시 흥덕구 오송읍",
        fare: 150000,
        pickupX: 127.0544,
        pickupY: 37.2592,
        dropoffX: 127.3276,
        dropoffY: 36.6213,
        itemDescription: "의료기기 샘플, 항온항습 차량 필수. VIP 보안콜.",
        companyName: "바이오로지스"
    }
];
